name: Auto Crawl DTU Schedule (Chrome)

on:
  schedule:
    # 1:30 AM VN (Sáng sớm) = 18:30 UTC hôm trước
    - cron: '30 18 * * *'
    
    # 6:00 AM VN (Sáng dậy) = 23:00 UTC hôm trước
    - cron: '0 23 * * *'
    
    # 11:30 AM VN (Tan học sáng) = 04:30 UTC
    - cron: '30 4 * * *'
    
    # 12:00 PM VN (Ăn trưa xong) = 05:00 UTC
    - cron: '0 5 * * *'

  workflow_dispatch: # Cho phép bấm chạy tay

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium ddddocr gitpython webdriver-manager

      - name: Run Crawler Script
        run: python crawl_schedule_to_json.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git pull origin main --rebase
          git add lich_hoc_hom_nay_va_mai.json
          git commit -m "Auto update: 1h30, 6h, 11h30, 12h" || exit 0
          git push
